[package]
authors = ["Daniel Wiesenberg <weasy@hotmail.de>"]
description = "Load and draw simple SVG files in Bevy."
edition = "2018"
license = "APACHE"
name = "bevy_svg"
readme = "README.md"
repository = "https://github.com/Weasy666/bevy_svg/"
version = "0.2.1"
keywords = ["gamedev", "graphics", "bevy", "svg"]
categories = ["Graphics", "Game engines", "Rendering"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", rev = "3319195f9036e9ee301545632b98f1090a3ba3b0", default-features = false, features = ["default", "trace"] }

lyon_geom = "0.17"
lyon_svg = "0.17"
lyon_tessellation = "0.17"
usvg = "0.14"

[dev-dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", rev = "3319195f9036e9ee301545632b98f1090a3ba3b0", default-features = true }
